### PR TITLE
update description

### PR DESCRIPTION
**Pull request by Trott**
Code & Learn has morphed a bit. Update description to more accurately
describe what goes on.

@mikeal @addaleax @hackygolucky

### CODE REVIEW

**Review by williamkapke — APPROVED** [review]

**Review by hackygolucky — APPROVED** [review]
🎉

**Comment by mikeal** [comment]
How are people feeling about the name "Code & Learn?"

Do we think this can be folded in or merged with Node TODO at some point?

**Comment by jasnell** [comment]
The "Code & Learn" name has always seemed a bit wonky to me. Definitely prefer "Node.js TODO" (the .js is silent ;-) ...)

**Comment by Fishrock123** [comment]
I like "Node TODO" better but maybe "Code & Learn" is a bit more clear?

**Comment by mikeal** [comment]
What about "Node.js First Commit" or "Node.js First PR" ?

**Pull request merged**
